# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='document_source_semantic_search',
    source=[
        'document_source_semantic_search.cpp'
    ],
    LIBDEPS_PRIVATE= [
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/pipeline/pipeline'
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/mongod_initializers',
        '$BUILD_DIR/mongo/s/mongos_initializers',
    ]
)