# -*- mode: python -*-

Import('env')

env = env.Clone()

env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME'] = 1

env.Library(
    target='mqlisp',
    source=[
        'document_source_letpipe.cpp',
        'document_source_cond.cpp',
        'document_source_expand.cpp',
    ],
    LIBDEPS_PRIVATE= [
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/pipeline/pipeline',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/mongod_initializers',
        '$BUILD_DIR/mongo/s/mongos_initializers',
    ]
)

