# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='document_source_letpipe',
    source=[
        'document_source_letpipe.cpp'
    ],
    LIBDEPS_PRIVATE= [
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/pipeline/pipeline',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/mongod_initializers',
        '$BUILD_DIR/mongo/s/mongos_initializers',
    ]
)

# env.Library(
#     target='expression_quote',
#     source=[
#         'expression_quote.cpp'
#     ],
#     LIBDEPS_PRIVATE= [
#         '$BUILD_DIR/mongo/base',
#         '$BUILD_DIR/mongo/db/pipeline/pipeline',
#     ],
#     LIBDEPS_DEPENDENTS=[
#         '$BUILD_DIR/mongo/db/mongod_initializers',
#         '$BUILD_DIR/mongo/s/mongos_initializers',
#     ]
# )

env.Library(
    target='document_source_eval',
    source=[
        'document_source_eval.cpp'
    ],
    LIBDEPS_PRIVATE= [
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/pipeline/pipeline',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/mongod_initializers',
        '$BUILD_DIR/mongo/s/mongos_initializers',
    ]
)
