# -*- mode: python -*-

Import('env')

env = env.Clone()

# TODO: Combine all libs into a single one

env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME'] = 1

env.Append(LINKFLAGS=[
    '-Wl,-rpath,/usr/lib'
])

env.Library(
    target='document_source_random_delay',
    source=[
        'document_source_random_delay.cpp'
    ],
    LIBDEPS_PRIVATE= [
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/pipeline/pipeline',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/mongod_initializers',
        '$BUILD_DIR/mongo/s/mongos_initializers',
    ]

)

env.Library(
    target='document_source_observe',
    source=[
        'document_source_observe.cpp'
    ],
    LIBDEPS_PRIVATE= [
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/pipeline/pipeline',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/mongod_initializers',
        '$BUILD_DIR/mongo/s/mongos_initializers',
    ]
)
