# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='source_connectors',
    source=[
        'change_stream_source_connector.cpp',
        'kafka_source_connector.cpp',
        'manual_insertion_source_connector.cpp',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/commands/standalone',
        '$BUILD_DIR/mongo/db/commands/stream_registry',
        '$BUILD_DIR/mongo/db/db_raii',
        '$BUILD_DIR/mongo/db/pipeline/pipeline'
    ],
    SYSLIBDEPS=[
        'cppkafka',
        'rdkafka',
    ],
)
